pipeline{
  agent any
  environment {
    AWS_ACCESS_KEY_ID     = credentials('amar_aws_access_key_id')
    AWS_SECRET_ACCESS_KEY = credentials('amar_aws_access_key')
    PATH = "${PATH}:${getTerraformPath()}"
  }
  stages{
    stage('AWS Config'){
            steps{
              sh 'aws configure set region us-east-1'
              sh 'aws sts get-caller-identity'
            }
        }
   // stage('S3 - create bucket'){
      //steps{
         //sh returnStatus: true, script: 'aws s3 mb terraform-tf-1212 --region=us-east-1'
      //}
   // }
    stage('terraform init'){
      steps{
        sh "terraform init"
      }
    }
    stage('terraform apply'){
      steps{
        sh returnStatus: true, script: 'terraform apply -auto-approve'
      }
    }
    stage('S3 - create bucket'){
      steps{
         sh returnStatus: true, script: 'aws s3 mb terraform-tf-1212 --region=us-east-1'
      }
    }
  }
}

def getTerraformPath(){
      def tfHome = tool name: 'Terraform-jenkins-amar', type: 'terraform'
      return tfHome
}

